version: "3.6"

services:
  node:
    image: node:20-alpine
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    command: "tail -f /dev/null"
